---
-name: MD5 calculate
  vars:
    md5_commands:
      ios: "verify /md5 {{ filename }}"
      nxos: "show file {{ filename }} md5sum"
  cli_command:
    command: "{{ md5_commands[ansible_network_os] }}"
  register: md5_output
