---
- name: firmware upgrade
  vars:
   patch_commands:
     ios: "verify /md5 {{ filename }}"
     # nxos: "install all nxos bootflash:{{  firmware_filename  }} non-interruptive"
     nxos: "show version"
  cli_command:
   command: "{{ patch_commands[ansible_network_os] }}"
   register: install_output

- name: print install result
  debug: 
    msg: "{{  install_output  }}"
