---
- name: Waiting For SSH port responsible
  wait_for:
    host: "{{ inventory_hostname }}"
    port: 22
    state: started
    timeout: 600
    delay: 100 
    sleep: 15

- name: Extra wait for TACACS
  pause:
    seconds: 30
    
- name: get current OS version
  cli_command:
    command: "show version"
  register: version_outputs
  failed_when: file_version not in  version_outputs.stdout
