---
- name: Waiting For {{  patch_tag  }} devices To Come Back Up
  wait_for:
    host: "{{ inventory_hostname }}"
    port: 22
    state: started
    timeout: 600
#    delay: 100 
    sleep: 15
    
- name: get current OS version
  cli_command:
    command: "show version"
  register: version_outputs
  failed_when: file_version not in  version_outputs.stdout
