- name: generate timestamp
  set_fact:
    timestamp_day: "{{ lookup('pipe','TZ=America/New_York date +%Y%m%d') }}"
    timestamp_sec: "{{ lookup('pipe','TZ=America/New_York date +%H%M%S') }}"
    timestamp: "{{ timestamp_day }}-{{ timestamp_sec }}â€œ
  run_once: true
  delegate_to: {{ delegate_host }}
