---
- name: firmware upgrade
  vars:
   patch_commands:
     ios: "verify /md5 {{ filename }}"
     nxos: "show file {{ filename }} md5sum"
  cli_command:
   command: "{{ patch_commands[ansible_network_os] }}"
  register: md5_output
