---
- name: firmware upgrade
  vars:
   patch_commands:
     ios: "verify /md5 {{ filename }}"
     nxos: "install all nxos bootflash:{{  firmware_filename  }} non-interruptive"
  cli_command:
   command: "{{ patch_commands[ansible_network_os] }}"
