---
- name: run cli command (Multiple vendor supports)
  hosts: all
  gather_facts: no
  connection: network_cli

  tasks:
    - name: run defined command from Extra variables
      cisco.nxos.nxos_config:
        lines: "{{ lines_line }}"
        parents: "{{ parents_line }}"
      register: config_output
      
